### ISSUE TITLE
Bug : Plate with 4 items + 1 item in Oven

### ISSUE THREAD

**Issue by wala8963** [csj/code-a-la-mode#63]
When a player has a dish with 4 items and use the oven's item, he will end up with a dish with 5 items.

**Comment by csj** [comment]
We also found that it's possible to simply add all five finished desserts to a plate: blueberries, chopped strawberries, ice cream, croissant, tart. While this was certainly never expected (and you can see this from the way the viewer renders the dishes), it isn't technically _wrong_ -- but no customer will ever pay for this!

**Comment by 2StepsFr0mHell** [comment]
We wrote in the statement that a plate couldn't contain more than 4 desserts though.
